version: '3'

services:

  example-app:
    image: drill4j/scala-spring-sample:0.1.0
    ports:
      - 8087:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=host.docker.internal:8090,agentId=ScalaExampleAgent,buildVersion=0.1.0,logLevel=INFO"
    volumes:
      - agent-files:/data

  agent-files:
    image: drill4j/java-agent:0.7.0-28
    volumes:
      - agent-files:/java-agent

volumes:
  agent-files:
